Repository lifeistech/toybox, pull requests merged in 2022-09, with the labels that each got.

#143 MKMapViewのtoyを追加
  MKMapView/MKMapView.xcodeproj/project.pbxproj
  MKMapView/MKMapView.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MKMapView/MKMapView.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MKMapView/MKMapView/AppDelegate.swift
  MKMapView/MKMapView/Assets.xcassets/AccentColor.colorset/Contents.json
  MKMapView/MKMapView/Assets.xcassets/AppIcon.appiconset/Contents.json
  MKMapView/MKMapView/Assets.xcassets/Contents.json
  MKMapView/MKMapView/Base.lproj/LaunchScreen.storyboard
  MKMapView/MKMapView/Base.lproj/Main.storyboard
  MKMapView/MKMapView/Info.plist
  MKMapView/MKMapView/SceneDelegate.swift
  MKMapView/MKMapView/ViewController.swift
Labels: milestone 1.5, 👾レビュー待ち

#151 KingfisherのtoyにReadmeとコードのコメントを追加
  Kingfisher-sample/Kingfisher-sample.xcodeproj/project.pbxproj
  Kingfisher-sample/Kingfisher-sample/ViewController.swift
  Kingfisher-sample/Kingfisher.png
  Kingfisher-sample/README.md
Labels: milestone 1.0, 👾レビュー待ち

#155 mainreadmeを更新
  README.md
Labels: milestone not set, 👾レビュー待ち
