Repository lifeistech/toybox, pull requests merged in 2022-10, with the labels that each got.

#165 about toyboxとScrapboxへのリンクをMain Readmeに追加
  README.md
Labels: milestone not set

#150 TrailingClosureのtoyにReadme, gif, コードのコメントを追加
  TrailingClosure/README.md
  TrailingClosure/TrailingClosure.gif
  TrailingClosure/TrailingClosure.xcodeproj/project.pbxproj
  TrailingClosure/TrailingClosure/ViewController.swift
Labels: milestone 1.0

#174 OptionalのReadmeを追加
  Optional/Optional.gif
  Optional/Optional.xcodeproj/project.pbxproj
  Optional/Optional/Base.lproj/Main.storyboard
  Optional/README.md
Labels: milestone 1.0, 修正対応待ち

#166 Do Try Catch
  DoTryCatch/DoTryCatch.xcodeproj/project.pbxproj
  DoTryCatch/DoTryCatch.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  DoTryCatch/DoTryCatch.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  DoTryCatch/DoTryCatch/AppDelegate.swift
  DoTryCatch/DoTryCatch/Assets.xcassets/AccentColor.colorset/Contents.json
  DoTryCatch/DoTryCatch/Assets.xcassets/AppIcon.appiconset/Contents.json
  DoTryCatch/DoTryCatch/Assets.xcassets/Contents.json
  DoTryCatch/DoTryCatch/Base.lproj/LaunchScreen.storyboard
  DoTryCatch/DoTryCatch/Base.lproj/Main.storyboard
  DoTryCatch/DoTryCatch/Info.plist
  DoTryCatch/DoTryCatch/SceneDelegate.swift
  DoTryCatch/DoTryCatch/ViewController.swift
Labels: milestone 1.5, 🦖レビュー待ち

#172 SwiftChartsのREADMEを追加
  SwiftCharts/README.md
  SwiftCharts/SwiftCharts.png
Labels: milestone 1.0

#170 UIHostingConfigurationのtoyにReadmeとコメントを追加
  UIHostingConfiguration/README.md
  UIHostingConfiguration/UIHostingConfiguration.gif
  UIHostingConfiguration/UIHostingConfiguration.xcodeproj/project.pbxproj
  UIHostingConfiguration/UIHostingConfiguration/ContentCell.swift
  UIHostingConfiguration/UIHostingConfiguration/ViewController.swift
Labels: milestone 1.0, 🦖レビュー待ち

#153 Feature/Generics
  Generics/Generics.xcodeproj/project.pbxproj
  Generics/Generics.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Generics/Generics.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Generics/Generics/AppDelegate.swift
  Generics/Generics/Assets.xcassets/AccentColor.colorset/Contents.json
  Generics/Generics/Assets.xcassets/AppIcon.appiconset/Contents.json
  Generics/Generics/Assets.xcassets/Contents.json
  Generics/Generics/Base.lproj/LaunchScreen.storyboard
  Generics/Generics/Base.lproj/Main.storyboard
  Generics/Generics/Info.plist
  Generics/Generics/SceneDelegate.swift
  Generics/Generics/ViewController.swift
Labels: milestone 1.5, 🦖レビュー待ち

#149 delegateのtoyにReadme, gif, コードのコメントを追加
  delegate/README.md
  delegate/delegate.gif
  delegate/delegate.xcodeproj/project.pbxproj
  delegate/delegate/CollectionViewCell.swift
  delegate/delegate/CollectionViewCellDelegate.swift
  delegate/delegate/ViewController+CollectionViewDelegate.swift
  delegate/delegate/ViewController.swift
Labels: milestone 1.0, 🦖レビュー待ち

#99 UIVisualEffectViewのtoyを追加
  UIVisualEffectView/UIVisualEffectView.xcodeproj/project.pbxproj
  UIVisualEffectView/UIVisualEffectView.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  UIVisualEffectView/UIVisualEffectView.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  UIVisualEffectView/UIVisualEffectView/AppDelegate.swift
  UIVisualEffectView/UIVisualEffectView/Assets.xcassets/AccentColor.colorset/Contents.json
  UIVisualEffectView/UIVisualEffectView/Assets.xcassets/AppIcon.appiconset/Contents.json
  UIVisualEffectView/UIVisualEffectView/Assets.xcassets/Contents.json
  UIVisualEffectView/UIVisualEffectView/Assets.xcassets/wallpaper.imageset/Contents.json
  UIVisualEffectView/UIVisualEffectView/Assets.xcassets/wallpaper.imageset/spring2022_sp_color.png
  UIVisualEffectView/UIVisualEffectView/Base.lproj/LaunchScreen.storyboard
  UIVisualEffectView/UIVisualEffectView/Base.lproj/Main.storyboard
  UIVisualEffectView/UIVisualEffectView/Info.plist
  UIVisualEffectView/UIVisualEffectView/SceneDelegate.swift
  UIVisualEffectView/UIVisualEffectView/ViewController.swift
Labels: milestone 1.5, 修正対応待ち
