Repository lifeistech/toybox, pull requests merged in 2022-08, with the labels that each got.

#116 Feature/trailing closure
  TrailingClosure/TrailingClosure.xcodeproj/project.pbxproj
  TrailingClosure/TrailingClosure.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  TrailingClosure/TrailingClosure.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  TrailingClosure/TrailingClosure/AppDelegate.swift
  TrailingClosure/TrailingClosure/Assets.xcassets/AccentColor.colorset/Contents.json
  TrailingClosure/TrailingClosure/Assets.xcassets/AppIcon.appiconset/Contents.json
  TrailingClosure/TrailingClosure/Assets.xcassets/Contents.json
  TrailingClosure/TrailingClosure/Base.lproj/LaunchScreen.storyboard
  TrailingClosure/TrailingClosure/Base.lproj/Main.storyboard
  TrailingClosure/TrailingClosure/Info.plist
  TrailingClosure/TrailingClosure/SceneDelegate.swift
  TrailingClosure/TrailingClosure/ViewController.swift
Labels: milestone 1.5, 👾レビュー待ち

#119 Feature/UI image picker
  UIImagePicker/README.md
  UIImagePicker/UIImagePicker.xcodeproj/project.pbxproj
  UIImagePicker/UIImagePicker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  UIImagePicker/UIImagePicker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  UIImagePicker/UIImagePicker/AppDelegate.swift
  UIImagePicker/UIImagePicker/Assets.xcassets/AccentColor.colorset/Contents.json
  UIImagePicker/UIImagePicker/Assets.xcassets/AppIcon.appiconset/Contents.json
  UIImagePicker/UIImagePicker/Assets.xcassets/Contents.json
  UIImagePicker/UIImagePicker/Base.lproj/LaunchScreen.storyboard
  UIImagePicker/UIImagePicker/Base.lproj/Main.storyboard
  UIImagePicker/UIImagePicker/Info.plist
  UIImagePicker/UIImagePicker/SceneDelegate.swift
  UIImagePicker/UIImagePicker/ViewController.swift
Labels: milestone 1.5, 🐢レビュー待ち, 👾レビュー待ち

#120 Feature/kingfisher
  Kingfisher-sample/Kingfisher-sample.xcodeproj/project.pbxproj
  Kingfisher-sample/Kingfisher-sample.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Kingfisher-sample/Kingfisher-sample.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Kingfisher-sample/Kingfisher-sample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Kingfisher-sample/Kingfisher-sample/AppDelegate.swift
  Kingfisher-sample/Kingfisher-sample/Assets.xcassets/AccentColor.colorset/Contents.json
  Kingfisher-sample/Kingfisher-sample/Assets.xcassets/AppIcon.appiconset/Contents.json
  Kingfisher-sample/Kingfisher-sample/Assets.xcassets/Contents.json
  Kingfisher-sample/Kingfisher-sample/Base.lproj/LaunchScreen.storyboard
  Kingfisher-sample/Kingfisher-sample/Base.lproj/Main.storyboard
  Kingfisher-sample/Kingfisher-sample/Info.plist
  Kingfisher-sample/Kingfisher-sample/SceneDelegate.swift
  Kingfisher-sample/Kingfisher-sample/ViewController.swift
  Kingfisher-sample/README.md
Labels: milestone 1.5, 🐢レビュー待ち, 👾レビュー待ち

#110 Feature/optional
  Optional/Optional.xcodeproj/project.pbxproj
  Optional/Optional.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Optional/Optional.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Optional/Optional/AppDelegate.swift
  Optional/Optional/Assets.xcassets/AccentColor.colorset/Contents.json
  Optional/Optional/Assets.xcassets/AppIcon.appiconset/Contents.json
  Optional/Optional/Assets.xcassets/Contents.json
  Optional/Optional/Base.lproj/LaunchScreen.storyboard
  Optional/Optional/Base.lproj/Main.storyboard
  Optional/Optional/Info.plist
  Optional/Optional/SceneDelegate.swift
  Optional/Optional/ViewController.swift
Labels: milestone 1.5, 👾レビュー待ち

#113 SwiftChartsのToyを追加
  SwiftCharts/SwiftCharts.xcodeproj/project.pbxproj
  SwiftCharts/SwiftCharts.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  SwiftCharts/SwiftCharts.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  SwiftCharts/SwiftCharts/Assets.xcassets/AccentColor.colorset/Contents.json
  SwiftCharts/SwiftCharts/Assets.xcassets/AppIcon.appiconset/Contents.json
  SwiftCharts/SwiftCharts/Assets.xcassets/Contents.json
  SwiftCharts/SwiftCharts/ContentView.swift
  SwiftCharts/SwiftCharts/Preview Content/Preview Assets.xcassets/Contents.json
  SwiftCharts/SwiftCharts/SwiftChartsApp.swift
  SwiftCharts/SwiftCharts/ToyShape.swift
Labels: milestone 1.5, 🦖レビュー待ち

#105 forのtoyを作成
  for/for.xcodeproj/project.pbxproj
  for/for.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  for/for.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  for/for/AppDelegate.swift
  for/for/Assets.xcassets/AccentColor.colorset/Contents.json
  for/for/Assets.xcassets/AppIcon.appiconset/Contents.json
  for/for/Assets.xcassets/Contents.json
  for/for/Base.lproj/LaunchScreen.storyboard
  for/for/Base.lproj/Main.storyboard
  for/for/Info.plist
  for/for/SceneDelegate.swift
  for/for/Transportation.swift
  for/for/ViewController.swift
Labels: milestone 1.5, 修正対応待ち

#118 enumのtoyを作成
  enum/enum.xcodeproj/project.pbxproj
  enum/enum.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  enum/enum.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  enum/enum/AppDelegate.swift
  enum/enum/Assets.xcassets/AccentColor.colorset/Contents.json
  enum/enum/Assets.xcassets/AppIcon.appiconset/Contents.json
  enum/enum/Assets.xcassets/Contents.json
  enum/enum/Base.lproj/LaunchScreen.storyboard
  enum/enum/Base.lproj/Main.storyboard
  enum/enum/Hours.swift
  enum/enum/Info.plist
  enum/enum/SceneDelegate.swift
  enum/enum/ViewController.swift
Labels: milestone 1.5, 👾レビュー待ち

#109 UIHostingConfigurationのToyを追加
  UIHostingConfiguration/UIHostingConfiguration.xcodeproj/project.pbxproj
  UIHostingConfiguration/UIHostingConfiguration.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  UIHostingConfiguration/UIHostingConfiguration.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  UIHostingConfiguration/UIHostingConfiguration/AppDelegate.swift
  UIHostingConfiguration/UIHostingConfiguration/Assets.xcassets/AccentColor.colorset/Contents.json
  UIHostingConfiguration/UIHostingConfiguration/Assets.xcassets/AppIcon.appiconset/Contents.json
  UIHostingConfiguration/UIHostingConfiguration/Assets.xcassets/Contents.json
  UIHostingConfiguration/UIHostingConfiguration/Base.lproj/LaunchScreen.storyboard
  UIHostingConfiguration/UIHostingConfiguration/Base.lproj/Main.storyboard
  UIHostingConfiguration/UIHostingConfiguration/ContentCell.swift
  UIHostingConfiguration/UIHostingConfiguration/Info.plist
  UIHostingConfiguration/UIHostingConfiguration/SceneDelegate.swift
  UIHostingConfiguration/UIHostingConfiguration/ViewController.swift
Labels: 🦖レビュー待ち, milestone 3.0 (HYPER)

#129 delegateのtoyを作成
  delegate/delegate.xcodeproj/project.pbxproj
  delegate/delegate.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  delegate/delegate.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  delegate/delegate/AppDelegate.swift
  delegate/delegate/Assets.xcassets/AccentColor.colorset/Contents.json
  delegate/delegate/Assets.xcassets/AppIcon.appiconset/Contents.json
  delegate/delegate/Assets.xcassets/Contents.json
  delegate/delegate/Base.lproj/LaunchScreen.storyboard
  delegate/delegate/Base.lproj/Main.storyboard
  delegate/delegate/CollectionViewCell.swift
  delegate/delegate/CollectionViewCell.xib
  delegate/delegate/CollectionViewCellDelegate.swift
  delegate/delegate/Info.plist
  delegate/delegate/SceneDelegate.swift
  delegate/delegate/ViewController+CollectionViewDelegate.swift
  delegate/delegate/ViewController.swift
Labels: milestone 1.5, 修正対応待ち

#141 UIFontの画像を16:9に更新
  UIFont/UIFont.png
Labels: milestone not set, 👾レビュー待ち

#117 MetalのComputeShaderを使ったメディアアートっぽいカウントアプリ
  ComputeShader/ComputeShader.xcodeproj/project.pbxproj
  ComputeShader/ComputeShader.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ComputeShader/ComputeShader.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ComputeShader/ComputeShader/AppDelegate.swift
  ComputeShader/ComputeShader/Assets.xcassets/AccentColor.colorset/Contents.json
  ComputeShader/ComputeShader/Assets.xcassets/AppIcon.appiconset/Contents.json
  ComputeShader/ComputeShader/Assets.xcassets/Contents.json
  ComputeShader/ComputeShader/Base.lproj/LaunchScreen.storyboard
  ComputeShader/ComputeShader/Base.lproj/Main.storyboard
  ComputeShader/ComputeShader/Info.plist
  ComputeShader/ComputeShader/Renderer.swift
  ComputeShader/ComputeShader/SceneDelegate.swift
  ComputeShader/ComputeShader/Shader.metal
  ComputeShader/ComputeShader/ShaderCore.swift
  ComputeShader/ComputeShader/ViewController.swift
Labels: milestone 1.5

#146 forのtoyにReadmeとコメントを追加
  for/README.md
  for/for.gif
  for/for.xcodeproj/project.pbxproj
  for/for/ViewController.swift
Labels: milestone 1.0, 👾レビュー待ち
