Repository lifeistech/toybox, pull requests merged in 2022-07, with the labels that each got.

#89 SwitchのtoyへコメントとReadmeを追加
  switch/README.md
  switch/switch.gif
  switch/switch.xcodeproj/project.pbxproj
  switch/switch/ViewController.swift
Labels: milestone 1.0

#94 CodableのtoyへコメントとReadmeを追加
  Codable/Codable.gif
  Codable/Codable.xcodeproj/project.pbxproj
  Codable/Codable/MemoData.swift
  Codable/Codable/ViewController.swift
  Codable/README.md
Labels: milestone 1.0

#90 extensionのコードにコメント、Readmeを追加
  extension/README.md
  extension/extension.gif
  extension/extension.xcodeproj/project.pbxproj
  extension/extension/DateExtension.swift
  extension/extension/UIViewExtension.swift
  extension/extension/ViewController.swift
Labels: milestone 1.0

#97 SFSymbolのtoyにReadmeを追加
  SFSymbol/README.md
  SFSymbol/SFSymbol.png
  SFSymbol/SFSymbol.xcodeproj/project.pbxproj
Labels: milestone 1.0

#96 ColorAssetのtoyにReadmeを追加
  ColorAsset/ColorAsset.png
  ColorAsset/ColorAsset.xcodeproj/project.pbxproj
  ColorAsset/ColorAsset/Base.lproj/Main.storyboard
  ColorAsset/README.md
Labels: milestone 1.0

#102 Main Readmeの更新
  README.md
Labels: milestone not set

#100 SpeechのtoyにReadmeを追加
  Speech/README.md
  Speech/Speech.png
  Speech/Speech.xcodeproj/project.pbxproj
  Speech/Speech/ViewController.swift
Labels: milestone 1.0

#103 ifのtoyを作成
  if/if.xcodeproj/project.pbxproj
  if/if.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  if/if.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  if/if/AppDelegate.swift
  if/if/Assets.xcassets/AccentColor.colorset/Contents.json
  if/if/Assets.xcassets/AppIcon.appiconset/Contents.json
  if/if/Assets.xcassets/Contents.json
  if/if/Base.lproj/LaunchScreen.storyboard
  if/if/Base.lproj/Main.storyboard
  if/if/Info.plist
  if/if/SceneDelegate.swift
  if/if/ViewController.swift
Labels: milestone 1.5

#95 feat: 関数をcomputed propertyに変更
  extension/extension/DateExtension.swift
  extension/extension/ViewController.swift
Labels: milestone not set, のこのこさんレビュー待ち
